version: 0.0
os: linux

files:
  - source: files/index.html
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: index.html
    owner: apache
    group: apache
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/deregister_from_elb.sh
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/webserver-start.sh
    - location: scripts/register_with_elb.sh

